import { useState } from 'react';
import { Button } from '../ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/card';
import { ArrowLeft, Upload, File as FileIcon, Loader2, Download, CalendarDays, FileCheck, GraduationCap, ClipboardList, Timer, CheckCircle2, User, Users, Beaker, Activity, FileText } from 'lucide-react';
import { Badge } from '../ui/badge';
import { downloadFile } from '../../lib/download';

export default function ProtocolToOps({ agent, onBack }: { agent: any, onBack: () => void }) {
    const [processing, setProcessing] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [activeTab, setActiveTab] = useState('schedule');
    const [file, setFile] = useState<File | null>(null);

    const handleAct = () => {
        setProcessing(true);
        setTimeout(() => {
            setProcessing(false);
            setResult(true);
        }, 3000);
    };

    const handleAddEventsToGoogle = () => {
        const today = new Date();
        const v1Date = new Date(today);
        v1Date.setDate(today.getDate() + 7);

        const visits = [
            { name: "Visit 1: Screening", daysOffset: 0, duration: 2, procedures: "Informed Consent, Demographics, Med Hx, VS, PE, ECG, Labs (CBC/CMP/Lipid), Urinalysis, Review I/E\n\nNotes: Ensure 12-hour fasting. Pregnancy test required." },
            { name: "Visit 2: Baseline", daysOffset: 14, duration: 1.5, procedures: "Confirm I/E, Randomize, Study Drug Dispense, VS, AE review, ConMed review" },
            { name: "Visit 3: Treatment Day 7", daysOffset: 21, duration: 1, procedures: "VS, AE review, ConMed review, Brief PE, Study Drug Compliance Check" },
            { name: "Visit 4: Treatment Day 14", daysOffset: 28, duration: 1, procedures: "VS, AE review, ConMed review, Study Drug Return/Dispense, Labs (CBC/CMP)" },
            { name: "Visit 5: Treatment Day 21", daysOffset: 35, duration: 1, procedures: "VS, AE review, ConMed review, Brief PE, Study Drug Compliance Check" },
            { name: "Visit 6: Treatment Day 28", daysOffset: 42, duration: 2, procedures: "VS, PE, ECG, Labs (CBC/CMP/Lipid), Urinalysis, AE/ConMed review, Final Drug Return\n\nNotes: Ensure 12-hour fasting." }
        ];

        visits.forEach((v, index) => {
            const startDate = new Date(v1Date);
            startDate.setDate(v1Date.getDate() + v.daysOffset);
            startDate.setHours(9, 0, 0, 0);

            const endDate = new Date(startDate);
            const durationMs = v.duration * 60 * 60 * 1000;
            endDate.setTime(startDate.getTime() + durationMs);

            const formatGoogleDate = (d: Date) => d.toISOString().replace(/-|:|\.\d\d\d/g, '');

            const text = encodeURIComponent(`DERM-110 - ${v.name}`);
            const details = encodeURIComponent(`Protocol: DERM-110\nIndication: Plaque Psoriasis\n\nPurpose and Procedures:\n${v.procedures}\n\nAuto-generated by Flo State Operations Generator.`);
            const dates = `${formatGoogleDate(startDate)}/${formatGoogleDate(endDate)}`;

            const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${text}&dates=${dates}&details=${details}`;

            setTimeout(() => {
                window.open(url, '_blank');
            }, index * 200);
        });
    };

    // Download handled by centralized utility

    const tabs = [
        { id: 'schedule', name: 'Visit Schedule', icon: CalendarDays },
        { id: 'documents', name: 'Doc Checklist', icon: FileCheck },
        { id: 'training', name: 'Role Training', icon: GraduationCap },
        { id: 'source', name: 'Source Docs', icon: ClipboardList },
        { id: 'burden', name: 'Burden Est.', icon: Timer },
    ];

    return (
        <div className="absolute inset-0 bg-slate-50 z-50 overflow-auto">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Button variant="ghost" onClick={onBack} className="mb-6 hover:bg-slate-200 transition-colors">
                    <ArrowLeft className="w-4 h-4 mr-2" /> Back to Store
                </Button>

                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                    <div className="flex items-center gap-4">
                        <div className="w-16 h-16 bg-blue-100 rounded-xl flex items-center justify-center text-blue-600 shadow-sm border border-blue-200">
                            <FileIcon size={32} />
                        </div>
                        <div>
                            <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-700 to-indigo-700">{agent.name}</h1>
                            <p className="text-slate-500 font-medium">{agent.description}</p>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                    <div className="lg:col-span-1 space-y-6">
                        <Card className="border-slate-200 shadow-sm rounded-2xl overflow-hidden">
                            <CardHeader className="bg-slate-50 border-b border-slate-100 pb-4">
                                <CardTitle className="text-lg">Generation Setup</CardTitle>
                            </CardHeader>
                            <CardContent className="pt-6">
                                <input type="file" id="protocol-ops-upload" className="hidden" onChange={(e) => setFile(e.target.files?.[0] || null)} />
                                <div onClick={() => document.getElementById('protocol-ops-upload')?.click()} className="border-2 border-dashed border-blue-200 rounded-xl p-6 text-center bg-blue-50/50 hover:bg-blue-50 transition-colors cursor-pointer mb-6">
                                    {file ? (
                                        <>
                                            <FileIcon className="w-8 h-8 text-blue-500 mx-auto mb-3" />
                                            <p className="text-sm font-semibold text-blue-900 truncate px-2">{file.name}</p>
                                        </>
                                    ) : (
                                        <>
                                            <Upload className="w-8 h-8 text-blue-400 mx-auto mb-3" />
                                            <p className="text-sm font-semibold text-blue-900">Upload Protocol</p>
                                        </>
                                    )}
                                </div>

                                <div className="space-y-4 mb-6">
                                    <div>
                                        <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2 block">Site Type</label>
                                        <select className="w-full bg-slate-100 border-none rounded-lg p-3 text-sm font-medium focus:ring-2 focus:ring-blue-500 outline-none">
                                            <option>Academic Medical Center</option>
                                            <option>Dedicated Research Site</option>
                                            <option>Community Hospital</option>
                                        </select>
                                    </div>
                                </div>

                                <Button
                                    className="w-full bg-slate-900 hover:bg-blue-600 text-white rounded-xl h-12 text-md font-semibold transition-all shadow-md"
                                    onClick={handleAct}
                                    disabled={processing}
                                >
                                    {processing ? <><Loader2 className="w-5 h-5 mr-3 animate-spin" /> Generating Plan...</> : 'Generate Ops Package'}
                                </Button>
                            </CardContent>
                        </Card>
                    </div>

                    <div className="lg:col-span-3">
                        <Card className="h-full min-h-[600px] border-slate-200 shadow-sm rounded-2xl overflow-hidden flex flex-col">
                            <CardHeader className="bg-white border-b border-slate-100 flex flex-row items-center justify-between pb-4">
                                <CardTitle className="text-lg">Operational Package Output</CardTitle>
                                {result && (
                                    <button
                                        type="button"
                                        onClick={() => downloadFile('/downloads/Visit_Schedule_Operations.csv', 'DERM110_Operations_Bundle.csv')}
                                        className="inline-flex items-center justify-center whitespace-nowrap text-sm bg-white border border-slate-200 hover:bg-slate-100 hover:text-slate-900 text-slate-900 rounded-lg shadow-sm font-medium h-9 px-3"
                                    >
                                        <Download className="w-4 h-4 mr-2" /> Export Operations Bundle
                                    </button>
                                )}
                            </CardHeader>
                            <CardContent className="p-0 flex-grow flex flex-col">
                                {!result && !processing && (
                                    <div className="flex-grow flex flex-col items-center justify-center text-slate-400 bg-slate-50/50">
                                        <FileIcon className="w-16 h-16 mb-4 opacity-20" />
                                        <p className="font-medium">Upload a protocol to generate operations plans.</p>
                                    </div>
                                )}

                                {processing && (
                                    <div className="flex-grow flex flex-col items-center justify-center bg-slate-50/50">
                                        <Loader2 className="w-12 h-12 mb-4 animate-spin text-blue-600" />
                                        <p className="mt-2 font-semibold text-blue-900 animate-pulse">Decomposing Protocol Syntax...</p>
                                        <p className="text-sm text-slate-500 mt-2">Correlating visits with required documentation</p>
                                    </div>
                                )}

                                {result && (
                                    <div className="flex-grow flex flex-col bg-slate-50/30">
                                        <div className="flex overflow-x-auto border-b border-slate-200 bg-white px-2 pt-2">
                                            {tabs.map((tab) => (
                                                <button
                                                    key={tab.id}
                                                    onClick={() => setActiveTab(tab.id)}
                                                    className={`flex items-center px-4 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${activeTab === tab.id
                                                        ? 'border-blue-600 text-blue-700'
                                                        : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
                                                        }`}
                                                >
                                                    <tab.icon className="w-4 h-4 mr-2" />
                                                    {tab.name}
                                                </button>
                                            ))}
                                        </div>

                                        <div className="p-6 overflow-auto">
                                            {activeTab === 'schedule' && (
                                                <div className="animate-in fade-in slide-in-from-bottom-2">
                                                    <div className="flex items-center justify-between mb-4">
                                                        <h3 className="text-lg font-bold">Participant Visit Schedule</h3>
                                                        <button
                                                            type="button"
                                                            onClick={handleAddEventsToGoogle}
                                                            className="inline-flex items-center justify-center whitespace-nowrap text-sm bg-blue-50 border border-blue-200 hover:bg-blue-100 hover:text-blue-700 text-blue-700 rounded-lg shadow-sm font-semibold h-9 px-3 transition-colors outline-none"
                                                        >
                                                            <CalendarDays className="w-4 h-4 mr-2" /> Add to Calendar
                                                        </button>
                                                    </div>
                                                    <div className="space-y-3">
                                                        {[1, 2, 3, 4, 5].map((v) => (
                                                            <div key={v} className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex items-center justify-between">
                                                                <div className="flex items-center gap-4">
                                                                    <div className="w-12 h-12 bg-blue-50 text-blue-700 rounded-lg flex flex-col items-center justify-center font-bold">
                                                                        <span className="text-xs uppercase opacity-70">Visit</span>
                                                                        <span>{v}</span>
                                                                    </div>
                                                                    <div>
                                                                        <p className="font-bold text-slate-800">{v === 1 ? 'Screening' : v === 2 ? 'Baseline' : `Treatment Day ${v * 7}`}</p>
                                                                        <p className="text-sm text-slate-500">Day {v === 1 ? '-14 to 0' : v === 2 ? '0' : v * 7} (± 2 days)</p>
                                                                    </div>
                                                                </div>
                                                                <div className="text-right">
                                                                    <Badge variant="outline" className="bg-indigo-50 text-indigo-700 border-indigo-200 mb-1">{v === 1 ? '8 Procedures' : '5 Procedures'}</Badge>
                                                                    <p className="text-xs text-slate-500 block">Est. 120 mins</p>
                                                                </div>
                                                            </div>
                                                        ))}
                                                    </div>
                                                </div>
                                            )}

                                            {activeTab === 'documents' && (
                                                <div className="animate-in fade-in slide-in-from-bottom-2">
                                                    <h3 className="text-lg font-bold mb-4">Required TMF/ISF Artifacts</h3>
                                                    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                                                        <table className="min-w-full divide-y divide-slate-200">
                                                            <thead className="bg-slate-50">
                                                                <tr>
                                                                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">TMF Zone</th>
                                                                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Artifact</th>
                                                                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Criticality</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody className="bg-white divide-y divide-slate-100">
                                                                <tr>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">02 - Central Trial</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">Investigator's Brochure</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap"><Badge className="bg-red-100 text-red-700 hover:bg-red-100">Essential</Badge></td>
                                                                </tr>
                                                                <tr>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">03 - Regulatory</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">FDA Form 1572</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap"><Badge className="bg-red-100 text-red-700 hover:bg-red-100">Essential</Badge></td>
                                                                </tr>
                                                                <tr>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">05 - Site Mgmt</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">Delegation of Authority</td>
                                                                    <td className="px-6 py-4 whitespace-nowrap"><Badge className="bg-red-100 text-red-700 hover:bg-red-100">Essential</Badge></td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            )}

                                            {activeTab === 'training' && (
                                                <div className="animate-in fade-in slide-in-from-bottom-2">
                                                    <h3 className="text-lg font-bold mb-4">Role-Based Training Matrix</h3>
                                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                                                            <div className="flex items-center justify-between mb-3">
                                                                <h4 className="font-bold text-slate-800 flex items-center"><User className="w-4 h-4 mr-2 text-indigo-500" /> Investigator / Sub-I</h4>
                                                                <Badge className="bg-amber-100 text-amber-700">4 Modules</Badge>
                                                            </div>
                                                            <ul className="text-sm space-y-2 text-slate-600">
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Protocol Fundamentals (V2.0)</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Investigator Brochure Review</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> eCRF Sign-off Procedures</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> SAE Reporting Workflows</li>
                                                            </ul>
                                                        </div>
                                                        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                                                            <div className="flex items-center justify-between mb-3">
                                                                <h4 className="font-bold text-slate-800 flex items-center"><Users className="w-4 h-4 mr-2 text-blue-500" /> Clinical Coordinator</h4>
                                                                <Badge className="bg-amber-100 text-amber-700">6 Modules</Badge>
                                                            </div>
                                                            <ul className="text-sm space-y-2 text-slate-600">
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Protocol Fundamentals (V2.0)</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Informed Consent Process</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Source Document Completion</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> eCRF Data Entry</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> PROM Management</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Sample Coordination</li>
                                                            </ul>
                                                        </div>
                                                        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                                                            <div className="flex items-center justify-between mb-3">
                                                                <h4 className="font-bold text-slate-800 flex items-center"><Beaker className="w-4 h-4 mr-2 text-emerald-500" /> Pharmacy Team</h4>
                                                                <Badge className="bg-amber-100 text-amber-700">3 Modules</Badge>
                                                            </div>
                                                            <ul className="text-sm space-y-2 text-slate-600">
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Pharmacy Manual Review</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> IP Receipt & Storage</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> IP Dispensing & Tracking</li>
                                                            </ul>
                                                        </div>
                                                        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                                                            <div className="flex items-center justify-between mb-3">
                                                                <h4 className="font-bold text-slate-800 flex items-center"><Activity className="w-4 h-4 mr-2 text-rose-500" /> Lab / Phlebotomy</h4>
                                                                <Badge className="bg-amber-100 text-amber-700">2 Modules</Badge>
                                                            </div>
                                                            <ul className="text-sm space-y-2 text-slate-600">
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> Lab Manual Ext. A</li>
                                                                <li className="flex items-start"><CheckCircle2 className="w-4 h-4 text-emerald-500 mr-2 shrink-0 mt-0.5" /> PK Sampling Details</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            )}
                                            {activeTab === 'source' && (
                                                <div className="animate-in fade-in slide-in-from-bottom-2">
                                                    <div className="flex items-center justify-between mb-4">
                                                        <h3 className="text-lg font-bold">Generated Source Document Templates</h3>
                                                        <Badge className="bg-emerald-100 text-emerald-700">7 Templates Ready</Badge>
                                                    </div>
                                                    <div className="space-y-3">
                                                        {[
                                                            { title: 'Inpatient Screening Checklist', type: 'Visit Guide', pages: 4, req: 'Required V1' },
                                                            { title: 'Informed Consent Documentation Note', type: 'Clinical Note', pages: 1, req: 'Required V1' },
                                                            { title: 'Vital Signs & ECG Worksheet', type: 'Worksheet', pages: 2, req: 'Required All' },
                                                            { title: 'PASI Scoring Sheet', type: 'Assessment', pages: 2, req: 'Required V2, V6' },
                                                            { title: 'Adverse Event Log', type: 'Log', pages: 1, req: 'Rolling' },
                                                            { title: 'Concomitant Medications Log', type: 'Log', pages: 1, req: 'Rolling' },
                                                            { title: 'Investigational Product Accountability', type: 'Pharmacy', pages: 1, req: 'Required V2-V6' },
                                                        ].map((doc, idx) => (
                                                            <button
                                                                type="button"
                                                                onClick={() => downloadFile('/downloads/DERM110_SourceTemplate.txt', `${doc.title.replace(/\s+/g, '_')}.txt`)}
                                                                key={idx}
                                                                className="w-full flex items-center justify-between p-3 bg-white border border-slate-200 rounded-lg hover:border-blue-300 hover:bg-slate-50 transition-colors shadow-sm cursor-pointer group outline-none focus:ring-2 focus:ring-blue-500"
                                                            >
                                                                <div className="flex items-center gap-3">
                                                                    <div className="p-2 bg-slate-50 text-slate-400 group-hover:text-blue-500 group-hover:bg-blue-50 rounded">
                                                                        <FileText className="w-5 h-5" />
                                                                    </div>
                                                                    <div>
                                                                        <p className="font-semibold text-slate-800 text-sm group-hover:text-blue-700">{doc.title}</p>
                                                                        <div className="flex gap-2 mt-0.5">
                                                                            <span className="text-xs text-slate-500">{doc.type}</span>
                                                                            <span className="text-xs text-slate-300">•</span>
                                                                            <span className="text-xs text-slate-500">{doc.pages} Pages</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div className="flex items-center gap-4">
                                                                    <Badge variant="outline" className="bg-slate-50">{doc.req}</Badge>
                                                                    <Download className="w-4 h-4 text-slate-300 group-hover:text-blue-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                                                                </div>
                                                            </button>
                                                        ))}
                                                    </div>
                                                </div>
                                            )}
                                            {activeTab === 'burden' && (
                                                <div className="animate-in fade-in slide-in-from-bottom-2">
                                                    <h3 className="text-lg font-bold mb-4">Site Burden Estimation</h3>
                                                    <div className="max-w-2xl bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
                                                        <div className="p-6 bg-slate-50 border-b border-slate-200">
                                                            <p className="text-sm font-medium text-slate-500 uppercase tracking-wider mb-1">Total Estimated Patient Time</p>
                                                            <div className="flex items-end gap-2 text-slate-800">
                                                                <span className="text-4xl font-extrabold">14.5</span>
                                                                <span className="text-lg font-medium text-slate-500 mb-1">Hours / Patient</span>
                                                            </div>
                                                        </div>
                                                        <div className="p-6 space-y-6">
                                                            <div>
                                                                <div className="flex justify-between text-sm mb-1">
                                                                    <span className="font-medium text-slate-700 flex items-center"><Activity className="w-4 h-4 mr-2 text-rose-500" /> Procedures / Assessments</span>
                                                                    <span className="font-bold text-slate-900">7.0 Hrs</span>
                                                                </div>
                                                                <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
                                                                    <div className="bg-rose-500 h-full w-[48%]"></div>
                                                                </div>
                                                                <p className="text-xs text-slate-500 mt-2">Driver: Frequent PK sampling and triplicate ECG requirements.</p>
                                                            </div>
                                                            <div>
                                                                <div className="flex justify-between text-sm mb-1">
                                                                    <span className="font-medium text-slate-700 flex items-center"><Users className="w-4 h-4 mr-2 text-blue-500" /> Staff Coordination</span>
                                                                    <span className="font-bold text-slate-900">5.5 Hrs</span>
                                                                </div>
                                                                <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
                                                                    <div className="bg-blue-500 h-full w-[38%]"></div>
                                                                </div>
                                                                <p className="text-xs text-slate-500 mt-2">Driver: Requires concurrent Investigator and Pharmacist availability for early visits.</p>
                                                            </div>
                                                            <div>
                                                                <div className="flex justify-between text-sm mb-1">
                                                                    <span className="font-medium text-slate-700 flex items-center"><FileText className="w-4 h-4 mr-2 text-amber-500" /> Documentation & eCRF</span>
                                                                    <span className="font-bold text-slate-900">2.0 Hrs</span>
                                                                </div>
                                                                <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
                                                                    <div className="bg-amber-500 h-full w-[14%]"></div>
                                                                </div>
                                                                <p className="text-xs text-slate-500 mt-2">Driver: High volume of ConMed log updates.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                )}
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </div>
        </div>
    );
}

